name: Tests

on: [push, pull_request]

env:
  plenary_org: GustavoKatel
  plenary_branch: condvar-table-remove

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - version: nightly
          - version: v0.7.2
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get today's date
        id: date
        run: |
          echo "::set-output name=date::$(date +%F)"

      - name: Restore from todays cache
        uses: actions/cache@v3
        id: cache
        with:
          path: _neovim
          key: ${{ runner.os }}-${{ matrix.version }}-${{ steps.date.outputs.date }}

      - name: Download neovim
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p _neovim
          curl -sL https://github.com/neovim/neovim/releases/download/${{ matrix.version }}/nvim-linux64.tar.gz | tar xzf - --strip-components=1 -C "${PWD}/_neovim"

      - name: Prepare
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/vendor/start
          ln -s $(pwd) ~/.local/share/nvim/site/pack/vendor/start

      - name: Checkout plenary
        run: |
          git clone --branch ${{ env.plenary_branch }} --depth 1 https://github.com/${{ env.plenary_org }}/plenary.nvim ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim

      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"
          nvim --version
          make test

